### ISSUE TITLE
higlass-manage ingest error

### ISSUE THREAD

**Issue by xinyangbing** [higlass/higlass-manage#65]
I recently updated to MacOSX Catalina and higlass-manage ingest stopped working, and is giving me this error:

xinyangbing$ higlass-manage ingest --assembly dm6 XYZ.mcool 
state True
Inferred filetype: cooler
Inferred datatype: matrix
state True
state True
Traceback (most recent call last):
  File "/Users/xinyangbing/miniconda3/bin/higlass-manage", line 8, in <module>
    sys.exit(cli())
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/higlass_manage/ingest.py", line 69, in ingest
    _ingest(
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/higlass_manage/ingest.py", line 122, in _ingest
    return import_file(
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/higlass_manage/common.py", line 204, in import_file
    os.makedirs(temp_dir)
  File "/Users/xinyangbing/miniconda3/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/Users/xinyangbing/miniconda3/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/Users/xinyangbing/miniconda3/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/Users/xinyangbing/miniconda3/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '/host_mnt'

Please help thank you!

**Comment by pkerpedjiev** [comment]
Working on it. I think this might be the same issue as https://github.com/higlass/higlass-manage/issues/65.

**Comment by pkerpedjiev** [comment]
Hey, so there's a Docker setting you can change to fix this behavior. It should be fixed by default in a future version;

https://github.com/docker/for-mac/issues/4859

**Comment by xinyangbing** [comment]
Hi Thank you for the quick fix. Unfortunately when I re-installed docker, now I cannot even start an instance of higlass-manage:
higlass-manage start
Traceback (most recent call last):
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/urllib3/response.py", line 696, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/urllib3/response.py", line 436, in _error_catcher
    yield
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/urllib3/response.py", line 763, in read_chunked
    self._update_chunk_length()
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/urllib3/response.py", line 700, in _update_chunk_length
    raise httplib.IncompleteRead(line)
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/requests/models.py", line 751, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/urllib3/response.py", line 571, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/urllib3/response.py", line 792, in read_chunked
    self._original_response.close()
  File "/Users/xinyangbing/miniconda3/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/urllib3/response.py", line 454, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyangbing/miniconda3/bin/higlass-manage", line 8, in <module>
    sys.exit(cli())
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/higlass_manage/start.py", line 134, in start
    _start(
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/higlass_manage/start.py", line 180, in _start
    hg_container = client.containers.get(hg_container_name)
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/docker/models/containers.py", line 887, in get
    resp = self.client.api.inspect_container(container_id)
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/docker/api/container.py", line 771, in inspect_container
    self._get(self._url("/containers/{0}/json", container)), True
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/docker/api/client.py", line 228, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 685, in send
    r.content
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/requests/models.py", line 829, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/requests/models.py", line 754, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

**Comment by pkerpedjiev** [comment]
Hmm, what version of higlass-manage do you have?

Could you try doing this `pip install urllib3 == 1.23 requests == 2.19.1`? and then trying again?

**Comment by xinyangbing** [comment]
Hi, 
I have higlass-manage-0.8.0. I tried what you suggested and am still getting the same error message. I also tried using another version of python (3.7), or reinstalling miniconda3 to no avail. I was delaying updating my MacOS to Catalina because last time I updated OS I also ran into a variety of problems running scripts on conda. These version specific issues are a huge problem...

**Comment by pkerpedjiev** [comment]
Ugh, that's really annoying. I'm sorry about that. Unfortunately I can't reproduce your error locally. I'll try a few more things this evening.

**Comment by pkerpedjiev** [comment]
In the meantime, just FYI, there's a hosted version of higlass that you can use at https://resgen.io. Depending on how much data you have, I can make you an account to use there. Just shoot me an email at pkerpedjiev@gmail.com if you're interested.

**Comment by xinyangbing** [comment]
Hi,
I am still unable to run higlass-manage successfully, and get the same error. Do you think that the version incompatibilities could be because of MacOS update to Catalina? I was thinking about re-installing back to previous MacOS versions to see if this could fix the problem, but obviously this is a bit extreme and would be more likely to try it if you think this is the underlying cause.

**Comment by pkerpedjiev** [comment]
Oh wow, I dropped the ball on this. I wouldn't downgrade to a previous version of OS X. 

Did you try modifying `response.py` in urllib3 as described here: https://github.com/psf/requests/issues/4248#issuecomment-408666274?

That thread makes me wonder if it isn't a problem with either Docker or higlass-server running on Docker. If modifying `response.py` doesn't work, I would suggest popping into our Slack channel (https://rb.gy/q9do1b) and I can help you debug.

**Comment by xinyangbing** [comment]
Hi I tried your suggestion of the urllib3 like so: 
pip install urllib3==1.23 requests==2.19.1 
Requirement already satisfied: urllib3==1.23 in ./miniconda3/lib/python3.8/site-packages (1.23)
Requirement already satisfied: requests==2.19.1 in ./miniconda3/lib/python3.8/site-packages (2.19.1)
Requirement already satisfied: idna<2.8,>=2.5 in ./miniconda3/lib/python3.8/site-packages (from requests==2.19.1) (2.7)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./miniconda3/lib/python3.8/site-packages (from requests==2.19.1) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in ./miniconda3/lib/python3.8/site-packages (from requests==2.19.1) (2020.6.20)

but I'm still getting the same error message:

higlass-manage start
Traceback (most recent call last):
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/urllib3/response.py", line 572, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/urllib3/response.py", line 331, in _error_catcher
    yield
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/urllib3/response.py", line 637, in read_chunked
    self._update_chunk_length()
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/urllib3/response.py", line 576, in _update_chunk_length
    raise httplib.IncompleteRead(line)
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/requests/models.py", line 749, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/urllib3/response.py", line 461, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/urllib3/response.py", line 665, in read_chunked
    self._original_response.close()
  File "/Users/xinyangbing/miniconda3/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/urllib3/response.py", line 349, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyangbing/miniconda3/bin/higlass-manage", line 8, in <module>
    sys.exit(cli())
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/higlass_manage/start.py", line 57, in start
    _start(temp_dir,
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/higlass_manage/start.py", line 84, in _start
    container = client.containers.get(container_name)
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/docker/models/containers.py", line 887, in get
    resp = self.client.api.inspect_container(container_id)
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/docker/api/container.py", line 771, in inspect_container
    self._get(self._url("/containers/{0}/json", container)), True
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/docker/api/client.py", line 228, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 525, in get
    return self.request('GET', url, **kwargs)
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 662, in send
    r.content
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/requests/models.py", line 827, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/Users/xinyangbing/miniconda3/lib/python3.8/site-packages/requests/models.py", line 752, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

I cannot drop into the Slack channel because my email host is not accepted into that channel. Could you add "princeton.edu" to the list? Thank you so much! I would really like to reclaim the usage of your tool because it's the best one I have found so far. 

David

**Comment by pkerpedjiev** [comment]
Hey, could you try this link: https://higlass.slack.com/join/shared_invite/zt-jnezdxlc-BoWErWNQ24ihV9epcb24JQ#/?

**Comment by pkerpedjiev** [comment]
So with regard to the libraries, the suggestion here https://github.com/psf/requests/issues/4248#issuecomment-408666274 continues after installing those versions by modifying the actual `response.py` library. You can do that like this.

1. Open Python and find the location of the urllib3 file

```
(base) toc2~(:|✔) % python
Python 3.8.3 (default, May 19 2020, 13:54:14)
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from urllib3 import response
>>> response.__file__
'/Users/pete/miniconda3/lib/python3.8/site-packages/urllib3/response.py'
```

2. Open that file in your favorite editor:

```
(base) toc2~(:|✔) % subl /Users/pete/miniconda3/lib/python3.8/site-packages/urllib3/response.py
```

3.  Find the `_update_chunk_length` function (ctrl-f). In that function, add the line that has # added this line at the end:

```
    def _update_chunk_length(self):
        # First, we'll figure out length of a chunk and then
        # we'll try to read it from socket.
        if self.chunk_left is not None:
            return
        line = self._fp.fp.readline()
        line = line.split(b';', 1)[0]
        line = (len(line)>0 and line or "0")     # added this line
        try:
            self.chunk_left = int(line, 16)
        except ValueError:
            # Invalid chunked protocol response, abort.
            self.close()
            raise httplib.IncompleteRead(line)
```

4. Save the file and try again with higlass-manage

**Comment by xinyangbing** [comment]
OMG it worked! Thank you SOOOO much! Super excited to use this awesome interface again!

**Comment by xinyangbing** [comment]
Hi sorry to bother you again, it seems I prematurely celebrated. While I can start higlass-manage, and the Docker port seems to be running fine, and I can see all the tilesets I've uploaded on the command-line, when I open the browser all I get is a blank webpage. Do you know what the problem could be? This is what I get when I run higlass-manage start:

higlass-manage start
Stopping previously running container
Pulling latest image... doneData directory: /Users/xinyangbing/hg-data
Temp directory: /tmp/higlass-docker
Starting... default 8989
Docker started: higlass-manage-container-default
sending request 1
Waiting to start (tilesets)...
sending request 2
Waiting to start (tilesets)...
sending request 3
Waiting to start (tilesets)...
sending request 4
Non 200 status code returned (502), waiting...
sending request 5
Non 200 status code returned (502), waiting...
sending request 6
Non 200 status code returned (502), waiting...
sending request 7
Non 200 status code returned (502), waiting...
sending request 8
Non 200 status code returned (502), waiting...
sending request 9
Non 200 status code returned (502), waiting...
sending request 10
Non 200 status code returned (502), waiting...
sending request 11
Non 200 status code returned (502), waiting...
sending request 12
Non 200 status code returned (502), waiting...
sending request 13
Non 200 status code returned (502), waiting...
sending request 14
public_data: True
Replaced js file
Started

**Comment by pkerpedjiev** [comment]
Are you going to `http://localhost:8989`?

Can you open the browser console (cmd-option-i in chrome) or through the browser menu and take a screenshot of what's in the console?

<img width="742" alt="image" src="https://user-images.githubusercontent.com/2143629/99838631-71f4db00-2b37-11eb-8435-18bbab5c48f8.png">

<img width="498" alt="image" src="https://user-images.githubusercontent.com/2143629/99838693-889b3200-2b37-11eb-813e-1fa65d281d12.png">

**Comment by xinyangbing** [comment]
<img width="1280" alt="Screen Shot 2020-11-21 at 11 39 15 AM" src="https://user-images.githubusercontent.com/55600546/99882411-54cf1380-2bee-11eb-8f4b-eb68effd7155.png">

**Comment by pkerpedjiev** [comment]
Could you post a screenshot of the network tab?

And of `http://localhost:8989/version.txt`?

**Comment by xinyangbing** [comment]
<img width="1280" alt="Screen Shot 2020-11-23 at 11 26 56 AM" src="https://user-images.githubusercontent.com/55600546/99987748-d5bd1500-2d7e-11eb-82ec-4d284557c414.png">
<img width="1280" alt="Screen Shot 2020-11-23 at 11 25 59 AM" src="https://user-images.githubusercontent.com/55600546/99987778-da81c900-2d7e-11eb-8ef2-2bd612614244.png">

**Comment by pkerpedjiev** [comment]
OK, I'm having a hard time figuring out what's going wrong so I'm going to update to the latest OS X version and try again.

In the meantime I'll mention that there's a hosted higlass instance with user management and some extra bells and whistles that you can use at http://resgen.io. If you're interested in trying it out shoot me an email at pkerpedjiev@gmail.com and I'd be happy to make you an account.

**Comment by pkerpedjiev** [comment]
So I just upgraded to Big Sur and managed to run higlass-manage without issue.

Perhaps one more thing to try would be to create a new conda environment and install `higlass-manage` from scratch (`conda install -c bioconda pysam; pip install higlass-manage`)?

**Comment by xinyangbing** [comment]
I tried installing from scratch in another environment, but it is still not showing anything when I load http://localhost:8989. Could it be a data source issue? When I was trying to fix the issue on my end, I copied some mcool files in the the "tmp", "hg-tmp", "hg-data" folders and was moving them around. Could I have mistakenly mixed some files up and now higlass-manage is unable to correctly load the instance? I've also had this happen before (website failing to load properly) when I tried removing old mcool files and was messing around with installing/reinstalling.

**Comment by pkerpedjiev** [comment]
I guess it could be a data source issue. You could try starting with `higlass-manage start --data-dir ~/other-directory` to verify that.

One more thing to try is to clear your cache. To do that go to your browser console and select "Application":

![image](https://user-images.githubusercontent.com/2143629/100169841-62a4c300-2e92-11eb-8a3d-d9be990774b7.png)

And then click on "Clear Storage" in the left bar and then "Clear site data":

![image](https://user-images.githubusercontent.com/2143629/100169901-8405af00-2e92-11eb-9922-e5e1284de7c7.png)

Once you've done that hold down the shift key and click the regular chrome (or firefox) reload button.

What's driving me nuts is that I think I've seen this error before but I can't quite remember where 😖

**Comment by xinyangbing** [comment]
Hey the clear cache thing fixed it! I am beyond ecstatic. Thank you so much for staying with me! Happy holidays.

**Comment by pkerpedjiev** [comment]
Oh wow. Great to hear and thanks so much for your help in diagnosing this!
Happy holidays to you too!
